/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interface;

/**
 *
 * @author ronan
 */
public class interface_cadenas extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(interface_cadenas.class.getName());

    /**
     * Creates new form interface_cadenas
     */
    public interface_cadenas() {
        initComponents();
        int[] code = new int[4];
        for (int i = 0; i < 4; i++) {
            code[i] = (int) (Math.random() * 10); // chiffre entre 0 et 9
        }
        int [] codeteste=new int [4];
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        text_intro = new javax.swing.JLabel();
        up_chiffre_3 = new javax.swing.JButton();
        up_chiffre_4 = new javax.swing.JButton();
        up_chiffre_2 = new javax.swing.JButton();
        up_chiffre_1 = new javax.swing.JButton();
        down_chiffre_4 = new javax.swing.JButton();
        down_chiffre_1 = new javax.swing.JButton();
        down_chiffre_2 = new javax.swing.JButton();
        down_chiffre_3 = new javax.swing.JButton();
        texte_chiffre_1 = new javax.swing.JLabel();
        texte_chiffre_2 = new javax.swing.JLabel();
        texte_chiffre_3 = new javax.swing.JLabel();
        texte_chiffre_4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        texte_lbl_nb_chiffres_exacts = new javax.swing.JLabel();
        texte_nb_chiffres_exacts = new javax.swing.JLabel();
        texte_lbl_nb_chiffres_haut = new javax.swing.JLabel();
        texte_nb_chiffres_haut = new javax.swing.JLabel();
        texte_lbl_nb_chiffres_bas = new javax.swing.JLabel();
        texte_nb_chiffres_bas = new javax.swing.JLabel();
        texte_tentatives = new javax.swing.JLabel();
        texte_score = new javax.swing.JLabel();
        bouton_recommencer = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        text_intro.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        text_intro.setText("Code en moins de  5 tentatives ! ");
        text_intro.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(text_intro, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 34, 300, 30));

        up_chiffre_3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        up_chiffre_3.setText("/\\");
            getContentPane().add(up_chiffre_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 70, 80, 40));

            up_chiffre_4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
            up_chiffre_4.setText("/\\");
                getContentPane().add(up_chiffre_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 70, 80, 40));

                up_chiffre_2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
                up_chiffre_2.setText("/\\");
                    up_chiffre_2.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                            up_chiffre_2ActionPerformed(evt);
                        }
                    });
                    getContentPane().add(up_chiffre_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, 80, 40));

                    up_chiffre_1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
                    up_chiffre_1.setText("/\\");
                        up_chiffre_1.addActionListener(new java.awt.event.ActionListener() {
                            public void actionPerformed(java.awt.event.ActionEvent evt) {
                                up_chiffre_1ActionPerformed(evt);
                            }
                        });
                        getContentPane().add(up_chiffre_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 80, 40));

                        down_chiffre_4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
                        down_chiffre_4.setText("\\/");
                        getContentPane().add(down_chiffre_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 200, 80, 40));

                        down_chiffre_1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
                        down_chiffre_1.setText("\\/");
                        getContentPane().add(down_chiffre_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 80, 40));

                        down_chiffre_2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
                        down_chiffre_2.setText("\\/");
                        getContentPane().add(down_chiffre_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, 80, 40));

                        down_chiffre_3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
                        down_chiffre_3.setText("\\/");
                        getContentPane().add(down_chiffre_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, 80, 40));

                        texte_chiffre_1.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
                        texte_chiffre_1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                        texte_chiffre_1.setText("0");
                        getContentPane().add(texte_chiffre_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 60, 90));

                        texte_chiffre_2.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
                        texte_chiffre_2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                        texte_chiffre_2.setText("0");
                        getContentPane().add(texte_chiffre_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 60, 90));

                        texte_chiffre_3.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
                        texte_chiffre_3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                        texte_chiffre_3.setText("0");
                        getContentPane().add(texte_chiffre_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 110, 60, 90));

                        texte_chiffre_4.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
                        texte_chiffre_4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                        texte_chiffre_4.setText("0");
                        getContentPane().add(texte_chiffre_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 110, 60, 90));

                        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
                        jButton1.setText("Tester");
                        jButton1.addActionListener(new java.awt.event.ActionListener() {
                            public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jButton1ActionPerformed(evt);
                            }
                        });
                        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 140, 100, 50));

                        texte_lbl_nb_chiffres_exacts.setText("Nombre de chiffres exacts :");
                        getContentPane().add(texte_lbl_nb_chiffres_exacts, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, -1, -1));

                        texte_nb_chiffres_exacts.setText("0");
                        getContentPane().add(texte_nb_chiffres_exacts, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 290, -1, -1));

                        texte_lbl_nb_chiffres_haut.setText("Nombre de chiffres trop hauts : ");
                        getContentPane().add(texte_lbl_nb_chiffres_haut, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, -1, -1));

                        texte_nb_chiffres_haut.setText("0");
                        getContentPane().add(texte_nb_chiffres_haut, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 320, -1, -1));

                        texte_lbl_nb_chiffres_bas.setText("Nobre de chiffres trop bas : ");
                        getContentPane().add(texte_lbl_nb_chiffres_bas, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 350, -1, -1));

                        texte_nb_chiffres_bas.setText("0");
                        getContentPane().add(texte_nb_chiffres_bas, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 350, -1, -1));

                        texte_tentatives.setText("Tentatives");
                        getContentPane().add(texte_tentatives, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 270, -1, -1));

                        texte_score.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
                        texte_score.setText("0 sur 5");
                        texte_score.setBorder(javax.swing.BorderFactory.createEtchedBorder());
                        getContentPane().add(texte_score, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 290, -1, -1));

                        bouton_recommencer.setText("Recommencer");
                        getContentPane().add(bouton_recommencer, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 340, -1, 40));

                        pack();
                    }// </editor-fold>//GEN-END:initComponents

    private void up_chiffre_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_up_chiffre_1ActionPerformed


    }//GEN-LAST:event_up_chiffre_1ActionPerformed

    private void up_chiffre_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_up_chiffre_2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_up_chiffre_2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new interface_cadenas().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bouton_recommencer;
    private javax.swing.JButton down_chiffre_1;
    private javax.swing.JButton down_chiffre_2;
    private javax.swing.JButton down_chiffre_3;
    private javax.swing.JButton down_chiffre_4;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel text_intro;
    private javax.swing.JLabel texte_chiffre_1;
    private javax.swing.JLabel texte_chiffre_2;
    private javax.swing.JLabel texte_chiffre_3;
    private javax.swing.JLabel texte_chiffre_4;
    private javax.swing.JLabel texte_lbl_nb_chiffres_bas;
    private javax.swing.JLabel texte_lbl_nb_chiffres_exacts;
    private javax.swing.JLabel texte_lbl_nb_chiffres_haut;
    private javax.swing.JLabel texte_nb_chiffres_bas;
    private javax.swing.JLabel texte_nb_chiffres_exacts;
    private javax.swing.JLabel texte_nb_chiffres_haut;
    private javax.swing.JLabel texte_score;
    private javax.swing.JLabel texte_tentatives;
    private javax.swing.JButton up_chiffre_1;
    private javax.swing.JButton up_chiffre_2;
    private javax.swing.JButton up_chiffre_3;
    private javax.swing.JButton up_chiffre_4;
    // End of variables declaration//GEN-END:variables
}
